"""Custom BigQuery and FinOps tools for the ADK agent.

What:
    Defines ADK agent tools for executing BigQuery SQL queries, retrieving billing schema metadata, running cost
    forecasts, and analyzing spending trends.

Why:
    Provides the primary data query interface for the FinOps agent, enabling natural language questions to be
    translated into optimized BigQuery queries with built-in security, caching, and result formatting.

How:
    Implements ``run_bigquery_query`` with thread-safe client management via ``BigQueryClientManager``, enforces
    user-accessible project filtering, converts complex data types to JSON-serializable structures, and caches
    query results in session state.
"""

import logging
import re
import threading
from datetime import date, datetime
from decimal import Decimal
from typing import Any

import google.auth
from google.adk.tools import ToolContext
from google.cloud import bigquery

from finops_agent.config import settings

logger = logging.getLogger(__name__)

# Global private in-memory query cache mapped by session_id to
# avoid serialising raw SQL caches into ADK SessionState
# Avoids heavy JSON serialisation overhead and OTEL trace bloat
_IN_MEMORY_BQ_CACHE: dict[str, dict[str, Any]] = {}


class BigQueryClientManager:
    """Manages thread-safe lazy-initialisation of the shared BigQuery client."""

    def __init__(self) -> None:
        self._bq_client = None
        self._bq_lock = threading.Lock()

    def get_client(self) -> bigquery.Client:
        """Returns the shared BigQuery client instance, building it if necessary."""
        if self._bq_client is None:
            with self._bq_lock:
                if self._bq_client is None:
                    credentials, _ = google.auth.default(
                        scopes=["https://www.googleapis.com/auth/bigquery"]
                    )
                    self._bq_client = bigquery.Client(
                        credentials=credentials,
                        project=settings.google_cloud_billing_project,
                    )
        return self._bq_client

    def reset(self) -> None:
        """Resets the cached BigQuery client."""
        with self._bq_lock:
            self._bq_client = None


# Module-level singleton instance for BigQuery client management
bq_client_manager = BigQueryClientManager()


def _get_bq_client() -> bigquery.Client:
    """Returns the shared BigQuery client instance, building it if necessary."""
    return bq_client_manager.get_client()


def _serialise_value(val: Any) -> Any:
    """Recursively serialises non-JSON-compliant data types (dates, decimals) for GenAI compatibility."""
    match val:
        case datetime() | date():
            return val.isoformat()
        case Decimal():
            return float(val)
        case dict():
            return {k: _serialise_value(v) for k, v in val.items()}
        case list():
            return [_serialise_value(v) for v in val]
        case _:
            return val


def execute_cached_bigquery_sql(sql: str, tool_context: ToolContext) -> list[dict]:
    """Executes a BigQuery SQL query against the billing export tables.

    This tool is highly optimised and uses in-memory caching to avoid redundant,
    expensive database table scans and minimise query costs.
    """
    logger.debug("Executing full BigQuery SQL query:\n%s", sql)
    try:
        # Import MagicMock locally to guard against mock autogeneration during unit testing
        from unittest.mock import MagicMock

        from finops_agent.app_utils.context import ALLOWED_PROJECTS_VAR

        # Retrieve allowed projects from ADK session state (saved up-front by before_agent_callback)
        allowed_projects = None
        state = getattr(tool_context, "state", None)
        # Avoid treating autogenerated MagicMock attributes as actual session state dictionaries
        if state is not None and not isinstance(state, MagicMock):
            allowed_projects = state.get("allowed_projects")

        # Fallback to context variable if not present in state
        if allowed_projects is None:
            allowed_projects_ctx = ALLOWED_PROJECTS_VAR.get()
            if allowed_projects_ctx is not None:
                allowed_projects = list(allowed_projects_ctx)

        # Fallback to user_id check
        if allowed_projects is None:
            user_email = tool_context.user_id
            if user_email and not isinstance(user_email, MagicMock):
                from finops_agent.app_utils.project_discovery import (
                    get_user_accessible_projects,
                )

                allowed_projects = list(get_user_accessible_projects(user_email))
                if state is not None and not isinstance(state, MagicMock):
                    state["allowed_projects"] = allowed_projects

        if allowed_projects is not None:
            # Dynamically scopes raw user-supplied SQL queries by replacing table references with pre-filtered subqueries.
            # Benefits:
            #   1. Security: Enforces multi-tenant project isolation at the database level by restricting rows
            #      to allowed_projects, preventing unauthorized data access.
            #   2. Performance & Cost Control: Pushes date filters down into the subqueries, enabling BigQuery
            #      partition pruning to avoid expensive full table scans and minimize query latency.
            #
            # Example Input:
            #   SELECT sku.description, SUM(cost) FROM `my_project.dataset.gcp_billing_export_v1_XXXX`
            #   WHERE usage_start_time >= '2026-07-01' AND project.id = 'my-app-dev'
            #
            # Example Scoped Output (assuming 'my-app-dev' is in allowed_projects):
            #   SELECT sku.description, SUM(cost) FROM (
            #       SELECT * FROM `my_project.dataset.gcp_billing_export_v1_XXXX`
            #       WHERE project.id IN ('my-app-dev') AND usage_start_time >= '2026-07-01'
            #   )
            #   WHERE usage_start_time >= '2026-07-01' AND project.id = 'my-app-dev'
            #
            # Inject project scoping filters dynamically into the query to prevent unauthorised access
            billing_suffix = settings.google_cloud_billing_account.replace("-", "_")
            standard_table = f"{settings.google_cloud_billing_project}.{settings.billing_export_dataset}.gcp_billing_export_v1_{billing_suffix}"
            resource_table = f"{settings.google_cloud_billing_project}.{settings.billing_export_dataset}.gcp_billing_export_resource_v1_{billing_suffix}"

            # Dynamic Table Routing: If the query references the resource table but does not query/filter
            # on resource properties, route to the standard table to avoid scanning massive volumes.
            if resource_table in sql and not re.search(r"\bresource\.", sql, re.IGNORECASE):
                sql = sql.replace(resource_table, standard_table)
                logger.info(
                    "Dynamically routed resource-level query to standard table (no resource fields referenced)."
                )

            sanitized_projects = [p for p in allowed_projects if re.match(r"^[a-z0-9\-]+$", p)]

            # Intersect with any explicit project ID filters present in the original SQL.
            # Benefits:
            #   1. Performance: Restricts the scoping filter strictly to the targeted project(s) (e.g. 'proj-1'
            #      instead of scanning all allowed_projects), accelerating BigQuery clustering scans.
            #   2. Security Auditing: Cross-references user-targeted projects against allowed_projects and
            #      flags attempts to query unauthorized project resources.
            #
            # Example Input:
            #   SELECT * FROM billing WHERE project.id = 'proj-1' (allowed: ['proj-1', 'proj-2'])
            #
            # Example Output Subquery:
            #   ... WHERE project.id IN ('proj-1') AND ...
            explicit_projects = set()
            eq_matches = re.findall(
                r"\bproject\.id\s*=\s*['\"]([a-z0-9\-]+)['\"]", sql, re.IGNORECASE
            )
            for p in eq_matches:
                explicit_projects.add(p)
            in_matches = re.findall(r"\bproject\.id\s*IN\s*\(([^)]+)\)", sql, re.IGNORECASE)
            for match in in_matches:
                for p in re.findall(r"['\"]([a-z0-9\-]+)['\"]", match, re.IGNORECASE):
                    explicit_projects.add(p)

            if explicit_projects:
                unauthorized_projects = explicit_projects - set(sanitized_projects)
                if unauthorized_projects:
                    logger.warning(
                        "Security warning: User attempted to query projects they do not have access to: %s",
                        list(unauthorized_projects),
                    )
                target_projects = [p for p in sanitized_projects if p in explicit_projects]
            else:
                target_projects = sanitized_projects

            # Extract date and partition filters to push them down into the subqueries.
            # Benefits:
            #   1. Performance: Pushing the date constraints directly inside the subqueries guarantees that
            #      BigQuery prunes partitions at the base scan level rather than evaluating full tables.
            #   2. Defensive Cost Protection: If no date filter is present, we defensively inject a 90-day
            #      limit to prevent accidental, expensive full historical scans.
            #
            # Example Input:
            #   SELECT * FROM billing WHERE usage_start_time >= '2026-07-01'
            #
            # Example Output Subquery:
            #   (SELECT * FROM table WHERE project.id IN (...) AND usage_start_time >= '2026-07-01')
            nested_parens = r"\((?:[^()]*|\((?:[^()]*|\((?:[^()]*|\([^()]*\))*\))*\))*\)"
            date_filter_pattern = re.compile(
                rf"\b(?:export_time|usage_start_time|usage_end_time)\s*(?:>=|<=|>|<|=)\s*(?:TIMESTAMP\s*{nested_parens}|TIMESTAMP_SUB\s*{nested_parens}|CAST\s*{nested_parens}|DATE_SUB\s*{nested_parens}|TIMESTAMP\s+['\"][^'\"]+['\"]|['\"][^'\"]+['\"]|\bCURRENT_DATE\b|\bCURRENT_TIMESTAMP\b)",
                re.IGNORECASE,
            )
            date_filters = date_filter_pattern.findall(sql)
            extra_where = " AND ".join(date_filters)
            if not extra_where:
                extra_where = "export_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY))"
                logger.warning(
                    "Defensively injected 90-day partition filter to prevent full historical scan."
                )

            if not target_projects:
                subquery_standard = f"(SELECT * FROM `{standard_table}` LIMIT 0)"
                subquery_resource = f"(SELECT * FROM `{resource_table}` LIMIT 0)"
            else:
                proj_list = ", ".join(f"'{p}'" for p in target_projects)
                where_clause = f"project.id IN ({proj_list})"
                if extra_where:
                    where_clause += f" AND {extra_where}"
                subquery_standard = f"(SELECT * FROM `{standard_table}` WHERE {where_clause})"
                subquery_resource = f"(SELECT * FROM `{resource_table}` WHERE {where_clause})"

            escaped_std = re.escape(standard_table)
            pattern_std = re.compile(rf"`{escaped_std}`|{escaped_std}")
            sql = pattern_std.sub(subquery_standard, sql)

            escaped_res = re.escape(resource_table)
            pattern_res = re.compile(rf"`{escaped_res}`|{escaped_res}")
            sql = pattern_res.sub(subquery_resource, sql)

        logger.debug("Scoped BigQuery SQL query:\n%s", sql)

        # Normalise SQL format to standardise cache keys
        normalised_sql = re.sub(r"\s+", " ", sql).strip()

        # Check in-memory query cache
        session_id = (
            tool_context.session.id
            if (tool_context.session and tool_context.session.id)
            else "default"
        )
        if session_id not in _IN_MEMORY_BQ_CACHE:
            _IN_MEMORY_BQ_CACHE[session_id] = {}
        bq_cache = _IN_MEMORY_BQ_CACHE[session_id]

        if normalised_sql in bq_cache:
            logger.debug("BQ Cache hit in memory for query: %s...", normalised_sql[:60])
            return bq_cache[normalised_sql]

        # Cache miss - execute the actual BigQuery query
        logger.debug("BQ Cache miss in memory for query: %s...", normalised_sql[:60])
        client = _get_bq_client()
        job = client.query(sql)
        rows = list(job.result())
        result = [{k: _serialise_value(v) for k, v in row.items()} for row in rows]
        logger.debug("BigQuery returned %d rows.", len(result))

        # Write to in-memory query cache
        bq_cache[normalised_sql] = result

        # Blackboard Auto-Caching: Automatically populates standard context keys on the session state
        # blackboard. This allows downstream subagents (e.g. RootCauseAnalyst, CloudAdvisor) to access
        # previously fetched analytical results directly, eliminating redundant BigQuery scans and
        # slashing multi-turn orchestration latency.
        # Examples of keys and value schemas populated:
        #   - 'daily_service_costs_30d': [{'usage_date': '2026-06-19', 'service_description': 'Cloud Run', 'daily_cost': 0.328, 'currency': 'GBP'}]
        #   - 'gcs_secret_waste': [{'resource_name': 'my-bucket', 'cost': 120.5, 'currency': 'GBP'}]
        #   - 'sku_period_costs_60d': [{'sku_description': 'VM', 'period_cost': 500.0, 'is_current_period': True, 'currency': 'GBP'}]
        if state is not None and not isinstance(state, MagicMock):
            norm_lower = normalised_sql.lower()
            interval_match = re.search(r"interval\s+(\d+)\s+day", norm_lower)
            days_suffix = f"_{interval_match.group(1)}d" if interval_match else ""

            if (
                "resource_name" in norm_lower
                and "cost" in norm_lower
                and ("secret manager" in norm_lower or "cloud storage" in norm_lower)
            ):
                state["gcs_secret_waste"] = result
                logger.info("Automatically cached 'gcs_secret_waste' in session state blackboard.")
            elif (
                "usage_date" in norm_lower
                and "service_description" in norm_lower
                and "daily_cost" in norm_lower
            ):
                key = f"daily_service_costs{days_suffix or '_30d'}"
                state[key] = result
                logger.info(f"Automatically cached '{key}' in session state blackboard.")
            elif (
                "is_current_period" in norm_lower
                and "sku_description" in norm_lower
                and "period_cost" in norm_lower
            ):
                key = f"sku_period_costs{days_suffix or '_60d'}"
                state[key] = result
                logger.info(f"Automatically cached '{key}' in session state blackboard.")

        return result
    except Exception as e:
        logger.error(f"Error in execute_cached_bigquery_sql tool: {e}", exc_info=True)
        raise e


def get_precomputed_root_cause(date_str: str, tool_context: ToolContext) -> dict[str, Any]:
    """Runs the comparative cost spike query in Python for the given date, correlates it with
    CAI configuration logs for any specific persistent resources, and returns the result.
    """
    import datetime

    from finops_agent.app_utils.cai_tools import get_cai_history_for_resource
    from finops_agent.client import resource_table_id

    target_date_str = date_str
    if not target_date_str or target_date_str.lower() in ("latest", "auto", "unknown", "today", "none", "null"):
        session_spikes = get_session_value("recentSpikes", tool_context)
        if session_spikes and isinstance(session_spikes, list) and len(session_spikes) > 0:
            peak_item = max(
                session_spikes,
                key=lambda item: sum(v for k, v in item.items() if k != "date" and isinstance(v, (int, float))),
            )
            target_date_str = peak_item.get("date", "")

    try:
        dt = datetime.datetime.strptime(target_date_str, "%Y-%m-%d").date()
    except Exception:
        dt = datetime.date.today() - datetime.timedelta(days=1)
    prev_dt = dt - datetime.timedelta(days=1)

    date_formatted = dt.strftime("%Y-%m-%d")
    prev_date_formatted = prev_dt.strftime("%Y-%m-%d")

    # comparative cost delta analysis between the spike date and the
    # preceding day at the individual resource level
    q = f"""
SELECT
  resource.name,
  SUM(CASE WHEN DATE(usage_start_time) = '{date_formatted}' THEN cost ELSE 0 END) as spike_day_cost,
  SUM(CASE WHEN DATE(usage_start_time) = '{prev_date_formatted}' THEN cost ELSE 0 END) as prev_day_cost,
  SUM(CASE WHEN DATE(usage_start_time) = '{date_formatted}' THEN cost ELSE 0 END) - SUM(CASE WHEN DATE(usage_start_time) = '{prev_date_formatted}' THEN cost ELSE 0 END) as cost_increase
FROM `{resource_table_id}`
WHERE export_time >= TIMESTAMP('{prev_date_formatted}')
  AND export_time < TIMESTAMP_ADD(TIMESTAMP('{date_formatted}'), INTERVAL 1 DAY)
  AND usage_start_time >= TIMESTAMP('{prev_date_formatted}')
  AND usage_start_time < TIMESTAMP_ADD(TIMESTAMP('{date_formatted}'), INTERVAL 1 DAY)
GROUP BY 1
HAVING spike_day_cost > 0.1 AND cost_increase > {settings.rca_cost_increase_threshold}
ORDER BY cost_increase DESC
LIMIT 5;
"""

    res = execute_cached_bigquery_sql(sql=q, tool_context=tool_context)

    resource_spikes = []
    has_persistent_resources = False

    for row in res:
        name = row.get("resource_name") or row.get("name")
        spike_cost = float(row.get("spike_day_cost", 0.0))
        prev_cost = float(row.get("prev_day_cost", 0.0))
        increase = float(row.get("cost_increase", 0.0))

        resource_info = {
            "name": name,
            "spike_day_cost": round(spike_cost, 2),
            "prev_day_cost": round(prev_cost, 2),
            "cost_increase": round(increase, 2),
            "cai_history": [],
        }

        if name and name.strip() and name.lower() != "null" and "/" in name:
            has_persistent_resources = True
            try:
                start_time_iso = f"{prev_date_formatted}T00:00:00Z"
                end_time_iso = f"{date_formatted}T23:59:59Z"
                cai_res = get_cai_history_for_resource(
                    resource_name=name,
                    start_time=start_time_iso,
                    end_time=end_time_iso,
                )
                resource_info["cai_history"] = cai_res
            except Exception as e:
                logger.error(f"Error fetching CAI history for {name}: {e}")

        resource_spikes.append(resource_info)

    summary_note = (
        f"Correlated {len(resource_spikes)} persistent resource spikes with CAI config logs."
        if has_persistent_resources
        else f"No resource-level cost spikes found for {date_formatted} compared to {prev_date_formatted}. Spend delta is attributable to general service/SKU-level usage."
    )

    return {
        "date": date_formatted,
        "previous_date": prev_date_formatted,
        "has_persistent_resources": has_persistent_resources,
        "resource_spikes": resource_spikes,
        "summary_note": summary_note,
    }


def get_precomputed_spend_analysis(
    days: int = 30, tool_context: ToolContext = None
) -> dict[str, Any]:
    """Pre-computes Month-to-Date (MTD) cloud costs, period-over-period trends, cost drivers,
    daily cost spikes, and Secret Manager/GCS zombie waste in Python for the given duration.
    Reuses cached BQ queries.
    """
    from finops_agent.client import resource_table_id, standard_table_id

    # 1. Daily Service-level Costs (Last N Days)
    q1 = f"""
SELECT
  DATE(usage_start_time) as usage_date,
  service.description as service_description,
  SUM(cost) as daily_cost,
  currency
FROM `{standard_table_id}`
WHERE export_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days} DAY))
  AND usage_start_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days} DAY))
GROUP BY 1, 2, 4
HAVING daily_cost > {settings.spend_analysis_daily_cost_threshold}
ORDER BY usage_date ASC;
"""

    # 2. SKU-level Period Costs (Last N*2 Days for period comparisons)
    q2 = f"""
SELECT
  usage_start_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days} DAY)) as is_current_period,
  project.id as project_id,
  service.description as service_description,
  sku.description as sku_description,
  SUM(cost) as period_cost,
  currency
FROM `{standard_table_id}`
WHERE export_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days * 2} DAY))
  AND usage_start_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days * 2} DAY))
GROUP BY 1, 2, 3, 4, 6
HAVING period_cost > {settings.spend_analysis_period_cost_threshold};
"""

    # 3. Storage and Secret waste (Last N Days)
    q3 = f"""
SELECT
  project.id as project_id,
  resource.name as resource_name,
  service.description as service_description,
  sku.description as sku_description,
  SUM(cost) as cost
FROM `{resource_table_id}`
WHERE export_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days} DAY))
  AND usage_start_time >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL {days} DAY))
  AND service.description IN ('Cloud Storage', 'Secret Manager')
  AND (
    service.description = 'Secret Manager'
    OR (service.description = 'Cloud Storage' AND (sku.description LIKE '%Storage%' OR sku.description LIKE '%Operation%'))
  )
GROUP BY 1, 2, 3, 4
HAVING cost > {settings.spend_analysis_waste_cost_threshold}
ORDER BY cost DESC;
"""

    res1 = execute_cached_bigquery_sql(sql=q1, tool_context=tool_context)
    res2 = execute_cached_bigquery_sql(sql=q2, tool_context=tool_context)
    res3 = execute_cached_bigquery_sql(sql=q3, tool_context=tool_context)

    currency = "GBP"
    if res2:
        currency = res2[0].get("currency", "GBP")

    # MTD Spend is calculated over the standard 30-day / current month window to keep card metrics consistent regardless of chart history days.
    import calendar
    import datetime

    today = datetime.date.today()
    cutoff_30d = (today - datetime.timedelta(days=30)).strftime("%Y-%m-%d")

    # 30-day MTD spend from daily breakdown
    mtd_spend = sum(
        float(row["daily_cost"])
        for row in res1
        if row.get("usage_date") and str(row["usage_date"]) >= cutoff_30d
    )

    prev_spend = sum(float(row["period_cost"]) for row in res2 if not row["is_current_period"])

    if prev_spend > 0:
        mtd_change = ((mtd_spend - prev_spend) / prev_spend) * 100.0
    else:
        mtd_change = 100.0

    days_in_month = calendar.monthrange(today.year, today.month)[1]
    elapsed_days = max(today.day, 1)
    daily_run_rate = mtd_spend / elapsed_days
    eom_forecast = mtd_spend + (daily_run_rate * (days_in_month - elapsed_days))

    if days > 30:
        months_count = max(days // 30, 1)
        forecast = eom_forecast * months_count
        forecast_label = f"Projected {months_count}-Month Forecast"
    else:
        forecast = eom_forecast
        forecast_label = "Projected end-of-month"

    drivers_curr = {}
    drivers_prev = {}
    for row in res2:
        key = (row["project_id"], row["service_description"])
        cost = float(row["period_cost"])
        if row["is_current_period"]:
            drivers_curr[key] = drivers_curr.get(key, 0.0) + cost
        else:
            drivers_prev[key] = drivers_prev.get(key, 0.0) + cost

    top_drivers = []
    for key, cost in drivers_curr.items():
        proj, svc = key
        prev = drivers_prev.get(key, 0.0)
        chg = 100.0 if prev == 0 else ((cost - prev) / prev) * 100.0
        top_drivers.append(
            {
                "project": proj,
                "service": svc,
                "cost": round(cost, 2),
                "change": round(chg, 1),
            }
        )
    top_drivers.sort(key=lambda x: x["cost"], reverse=True)

    daily_groups = {}
    services_seen = set()
    for row in res1:
        date_str = str(row["usage_date"])
        svc = row["service_description"]
        cost = float(row["daily_cost"])

        if "-" in date_str:
            parts = date_str.split("-")
            date_formatted = f"{parts[1]}/{parts[2]}"
        else:
            date_formatted = date_str

        if date_formatted not in daily_groups:
            daily_groups[date_formatted] = {}
        daily_groups[date_formatted][svc] = daily_groups[date_formatted].get(svc, 0.0) + cost
        services_seen.add(svc)

    recent_spikes = []
    for dt, svcs in daily_groups.items():
        total_day_cost = sum(svcs.values())
        if total_day_cost > 0.50:
            day_dict = {"date": dt}
            for s in services_seen:
                day_dict[s] = round(svcs.get(s, 0.0), 2)
            recent_spikes.append(day_dict)
    recent_spikes.sort(key=lambda x: x["date"])

    zombie_waste = 0.0
    zombies = []
    for row in res3:
        cost = float(row["cost"])
        zombie_waste += cost
        zombies.append(
            {
                "resource": row["resource_name"],
                "service": row["service_description"],
                "cost": round(cost, 2),
                "recommendation": "Review unused secret versions"
                if row["service_description"] == "Secret Manager"
                else "Clean up empty bucket storage",
            }
        )

    return {
        "currency": currency,
        "mtdSpend": round(mtd_spend, 2),
        "mtdChange": round(mtd_change, 1),
        "forecast": round(forecast, 2),
        "forecastLabel": forecast_label,
        "anomaliesCount": len(
            [s for s in recent_spikes if sum(v for k, v in s.items() if k != "date") > 2.0]
        ),
        "zombieWaste": round(zombie_waste, 2),
        "top_drivers": top_drivers,
        "recentSpikes": recent_spikes,
        "zombies": zombies,
    }


def get_session_value(key: str, tool_context: ToolContext) -> Any:
    """Retrieves a cached value from the active session state if present.
    Supported keys include:
    - 'allowed_projects': list of allowed project IDs
    - 'active_billing_projects': list of active billing projects
    - 'gcs_secret_waste': list or dict containing cached GCS/Secret Manager waste resources
    - 'daily_service_costs_30d'
    - 'sku_period_costs_60d'
    - 'zombie_resources'
    - 'rightsizing_recommendations'
    - 'spend_analysis'
    """
    from unittest.mock import MagicMock

    state = getattr(tool_context, "state", None)
    if state is not None and not isinstance(state, MagicMock):
        if key in state:
            logger.debug(
                f"[BLACKBOARD HIT] Retrieved key '{key}' from session state, skipping external tool query."
            )
            return state[key]
    logger.debug(f"[BLACKBOARD MISS] Key '{key}' not found in session state.")
    return None


def set_session_value(key: str, value: Any, tool_context: ToolContext) -> str:
    """Stores a value in the active session state for other agents to reuse in the current session.
    For example, use this to store 'gcs_secret_waste' so other agents do not have to query it again.
    """
    from unittest.mock import MagicMock

    state = getattr(tool_context, "state", None)
    if state is not None and not isinstance(state, MagicMock):
        state[key] = value
        logger.debug(
            f"[BLACKBOARD WRITE] Stored key '{key}' in session state for other subagents to reuse."
        )
        return f"Successfully stored key '{key}' in session state."
    return "Error: Session state not available."


BLACKBOARD_KEY_INSTRUCTIONS = """
CRITICAL: SHARED SESSION BLACKBOARD PATTERN
All subagents share a common session-scoped blackboard. Before calling external database queries, API calls, or MCP tools, you MUST check if the required data is already cached in the blackboard by calling `get_session_value(key)`. If it is present, use it directly.

Note: To prevent long response delays, do NOT call `set_session_value` to write BigQuery query results (like costs or waste lists) back to the session state; the query tool automatically caches these results in the session state for you under the appropriate keys when executed. Only call `set_session_value` for non-database results.

You MUST use these exact standardized keys:
- 'daily_service_costs_30d': List of daily service cost aggregates (date, service, cost) over the last 30 days.
- 'sku_period_costs_60d': List of SKU period costs (is_current_period, project, service, SKU, cost) over the last 60 days.
- 'gcs_secret_waste': List of inactive storage buckets (GCS) and Secret Manager version replicas.
- 'zombie_resources': List of idle static IPs and unattached boot/data disks.
- 'rightsizing_recommendations': Cost, rightsizing, and performance optimization suggestions from Cloud Assist.
"""
