"""Pydantic schemas and data models for application feedback and subagent outputs.

What:
    Defines shared Pydantic models (such as ``Feedback`` and ``TaskOutput``) used across the API backend
    and subagent task execution workflows.

Why:
    Provides explicit data validation, structured schema definitions, and typing contracts for API request/response
    bodies and subagent completion responses.

How:
    Extends Pydantic's ``BaseModel`` with field defaults, type hints, and descriptions tailored for feedback logging
    and task mode outputs.
"""

import uuid
from typing import (
    Literal,
)

from pydantic import (
    BaseModel,
    Field,
)


class Feedback(BaseModel):
    """Represents feedback for a conversation."""

    score: int | float
    text: str | None = ""
    log_type: Literal["feedback"] = "feedback"
    service_name: Literal["app"] = "app"
    user_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))


class TaskOutput(BaseModel):
    """Pydantic schema for task mode subagent completions via finish_task."""

    result: str = Field(
        description="The complete final markdown report and structured A2UI code block payloads generated by the subagent."
    )

